on: [push]

# the name of our workflow
name: ci

jobs:
    linting:
        name: Linting
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "lts/*"
            - name: Install dependencies
              run: npm install
            # - name: Lint
            #   run: npm run lint
    test:
        name: Testing
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - name: Tauri dependencies
              run: |
                  sudo apt update && sudo apt install -y \
                    libwebkit2gtk-4.1-dev \
                    build-essential \
                    curl \
                    wget \
                    file \
                    libxdo-dev \
                    libssl-dev \
                    libayatana-appindicator3-dev \
                    librsvg2-dev

            - name: Setup rust-toolchain stable
              id: rust-toolchain
              uses: dtolnay/rust-toolchain@stable

            - name: Cargo test
              run: cd src-tauri/ && cargo test && cd ..
