name: "release"
on:
    workflow_dispatch:

jobs:
    create-release:
        permissions:
            contents: write
            pull-requests: write
        runs-on: ubuntu-22.04
        outputs:
            release_id: ${{ steps.create-release.outputs.result }}
            new_version: ${{ steps.auto-increment-version.outputs.new_version }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "lts/*"

            - name: Auto-increment version
              id: auto-increment-version
              run: |
                  # Get current version
                  CURRENT_VERSION=$(node -p "require('./package.json').version")
                  echo "Current version: $CURRENT_VERSION"

                  # Parse version parts
                  IFS='.' read -ra VERSION_PARTS <<< "$CURRENT_VERSION"
                  MAJOR=${VERSION_PARTS[0]}
                  MINOR=${VERSION_PARTS[1]}
                  PATCH=${VERSION_PARTS[2]}

                  # Increment patch version
                  NEW_PATCH=$((PATCH + 1))
                  NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
                  echo "New version: $NEW_VERSION"

                  # Set up git user
                  git config --global user.name "GitHub Actions"
                  git config --global user.email "actions@github.com"

                  # Create a new branch for the version bump
                  git checkout -b version-bump-$NEW_VERSION

                  # Update package.json with new version
                  npm version $NEW_VERSION --no-git-tag-version

                  # Commit changes to the new branch
                  git add package.json
                  git commit -m "Bump version to $NEW_VERSION"
                  git push -u origin version-bump-$NEW_VERSION

                  # Output the new version for later steps
                  echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
                  echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
                  echo "BRANCH_NAME=version-bump-$NEW_VERSION" >> $GITHUB_ENV

            - name: Create pull request
              id: create-pr
              uses: actions/github-script@v6
              with:
                  script: |
                      const { data } = await github.rest.pulls.create({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        title: `Bump version to ${process.env.NEW_VERSION}`,
                        body: 'Automated version bump for new release',
                        head: `version-bump-${process.env.NEW_VERSION}`,
                        base: 'main',
                        draft: false
                      });

                      // Store PR number for later
                      console.log(`Created PR #${data.number}`);
                      return data.number;
                  result-encoding: string

            - name: Enable auto-merge for pull request
              uses: actions/github-script@v6
              with:
                  script: |
                      try {
                        // Try to enable auto-merge
                        await github.rest.pulls.updateBranch({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          pull_number: ${{ steps.create-pr.outputs.result }}
                        });
                        
                        console.log('PR branch updated with latest changes');
                      } catch (e) {
                        console.log('Error updating PR branch:', e);
                      }

                      try {
                        // Try to enable auto-merge with merge method
                        await github.rest.pulls.enableAutoMerge({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          pull_number: ${{ steps.create-pr.outputs.result }},
                          merge_method: 'squash'
                        });
                        console.log('Auto-merge enabled');
                      } catch (e) {
                        console.log('Could not enable auto-merge. You may need to merge it manually:', e);
                      }

            - name: Wait for PR merge
              run: |
                  # Wait up to 5 minutes for the PR to be merged
                  for i in {1..30}; do
                    PR_STATUS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                     "https://api.github.com/repos/${{ github.repository }}/pulls/${{ steps.create-pr.outputs.result }}" | \
                     jq -r '.state')

                    if [ "$PR_STATUS" = "closed" ]; then
                      echo "PR has been merged or closed"
                      break
                    fi
                    
                    echo "Waiting for PR to be merged... ($i/30)"
                    sleep 10
                  done

                  # Check if the branch was actually merged into main
                  git fetch origin
                  if git branch -r --contains origin/version-bump-${{ env.NEW_VERSION }} | grep -q "origin/main"; then
                    echo "Version branch was successfully merged to main"
                  else
                    echo "WARNING: Version branch does not appear to be merged to main yet"
                    echo "Please merge the PR manually before proceeding"
                    # Don't fail the workflow, as we may want to continue with the release anyway
                  fi

            - name: Create release
              id: create-release
              uses: actions/github-script@v6
              with:
                  script: |
                      const { data } = await github.rest.repos.createRelease({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        tag_name: `v${process.env.NEW_VERSION}`,
                        name: `v${process.env.NEW_VERSION}`,
                        body: '*This release was automatically generated with auto-incremented version.*',
                        draft: true,
                        prerelease: false,
                        target_commitish: 'main'
                      })
                      return data.id

    build-tauri:
        needs: create-release
        permissions:
            contents: write
        strategy:
            fail-fast: false
            matrix:
                include:
                    - platform: "macos-latest"
                      args: "--target aarch64-apple-darwin"
                    - platform: "macos-latest"
                      args: "--target x86_64-apple-darwin"
                #   - platform: 'ubuntu-22.04'
                #     args: ''
                #   - platform: 'windows-latest'
                #     args: ''

        runs-on: ${{ matrix.platform }}
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: main
                  fetch-depth: 0

            - name: setup node
              uses: actions/setup-node@v4
              with:
                  node-version: lts/*

            - name: install Rust stable
              uses: dtolnay/rust-toolchain@stable
              with:
                  targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

            - name: install dependencies (ubuntu only)
              if: matrix.platform == 'ubuntu-22.04'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

            - name: install frontend dependencies
              run: npm install

            - name: transform URLs for production
              run: |
                  if [[ "${{ matrix.platform }}" == "windows-latest" ]]; then
                    sed -i 's|"http://localhost:3000/\([^"]*\)"|"\1.html"|g' src-tauri/src/lib.rs
                  else
                    sed -i '' 's|"http://localhost:3000/\([^"]*\)"|"\1.html"|g' src-tauri/src/lib.rs
                  fi
                  echo "Modified lib.rs for production build:"
                  cat src-tauri/src/lib.rs

            - uses: tauri-apps/tauri-action@v0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  releaseId: ${{ needs.create-release.outputs.release_id }}
                  tagName: v${{ needs.create-release.outputs.new_version }}
                  releaseName: v${{ needs.create-release.outputs.new_version }}

    publish-release:
        permissions:
            contents: write
        runs-on: ubuntu-22.04
        needs: [create-release, build-tauri]

        steps:
            - name: Publish release
              id: publish-release
              uses: actions/github-script@v6
              env:
                  release_id: ${{ needs.create-release.outputs.release_id }}
              with:
                  script: |
                      github.rest.repos.updateRelease({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        release_id: process.env.release_id,
                        draft: false,
                        prerelease: false
                      })
